name: PR Build

on: [ pull_request ]

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx2g -Xms2g

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Show version info
      run: ./gradlew --version
    - name: List of generated files before
      run: find keel-sql/src/generated || true
    - name: current directory location
      run: echo $PWD
    - name: Generate source
      run: ./gradlew generateJooqMetamodel
    - name: List of generated files after
      run: find keel-sql/src/generated
    - name: List gradle files
      run: ls ~/.gradle